### ISSUE TITLE
[FEAT] 홈 View 구현

### ISSUE THREAD

**Issue by papajj06** [TeamFILL-IN/Fill-Android#12]
# 📝 DESCRIPTION
### Home **View** 구현

# ☑️ TODO
- [x] 상단 설명
- [x] 상단 탭
- [x] AROND YOU
- [x] new photo
- [x] 하단 팝업창
- [x] Map뷰 넣기

**Comment by l2hyunwoo** [comment]
@papajj06 이슈를 잡은 단위가 너무 큰 것 같아! 홈화면 구현이 어느 범위에서의 구현(View/기능/서버까지?)인지 명시해주면 좀 더 좋을 것 같음
